CREATE DATABASE auth_service;
CREATE DATABASE concert_service;
CREATE DATABASE reservation_service;
CREATE DATABASE payment_service;
CREATE DATABASE ticket_service;
CREATE DATABASE patient_service;
CREATE DATABASE appointment_service;
CREATE DATABASE prescription_service;
CREATE DATABASE notification_service;
